version: '3'

services:
    # empcontrol_backend:
    #     depends_on:
    #         - db
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     image: empcontrol-backend
    #     container_name: empcontrol-backend
    #     restart: always
    #     ports:
    #         - ${PORT}:${PORT}
    #     environment:
    #         PORT: ${PORT}

    postgres:
        image: postgres
        container_name: postgres1
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${DATABASE_PORT}:5432
        # volumes:
        #     - ./postgres:/var/lib/postgresql/data

    pgadmin:
        depends_on:
            - postgres
        image: dpage/pgadmin4
        container_name: pgadmin1
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@example.com"
            PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
        ports:
            - 8200:80